// Visual check: screenshots of the main screens (light + dark). Serves docs/ on 8081.
//   python3 tools/build.py http://127.0.0.1:8787 && node tests/shots.js [outdir]
const http = require('http'), fs = require('fs'), path = require('path');
const { chromium } = require('playwright');
const ROOT = path.resolve(__dirname, '..'), DOCS = path.join(ROOT, 'docs');
const OUT = path.resolve(process.argv[2] || path.join(ROOT, 'tests', 'shots', 'ui'));
fs.mkdirSync(OUT, { recursive: true });
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.json': 'application/json', '.webmanifest': 'application/manifest+json', '.png': 'image/png' };
const server = http.createServer((req, res) => {
  let p = decodeURIComponent(req.url.split('?')[0]); if (p.endsWith('/')) p += 'index.html';
  const f = path.join(DOCS, p);
  if (!f.startsWith(DOCS) || !fs.existsSync(f) || fs.statSync(f).isDirectory()) { res.writeHead(404); res.end(); return; }
  res.writeHead(200, { 'content-type': MIME[path.extname(f)] || 'application/octet-stream' }); fs.createReadStream(f).pipe(res);
});
(async () => {
  await new Promise((r) => server.listen(8081, '127.0.0.1', r));
  const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
  const dark = process.env.DARK === '1';
  const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, colorScheme: dark ? 'dark' : 'light' });
  const page = await ctx.newPage();
  const errors = [];
  page.on('pageerror', (e) => errors.push(e.message));
  const shot = async (n) => { await page.waitForTimeout(400); return page.screenshot({ path: path.join(OUT, n + (dark ? '-dark' : '') + '.png') }); };
  await page.goto('http://127.0.0.1:8081/', { waitUntil: 'load' });
  await page.waitForSelector('h1');
  await shot('01-home-fresh');
  await page.click('button:has-text("Set up your table")');
  await page.waitForSelector('#pn0');
  await shot('02-setup');
  for (let i = 0; i < 4; i++) await page.fill('#pn' + i, ['Ah Mei', 'Budi', 'Chris', 'Dewi'][i]);
  await shot('02b-setup-filled');
  await page.click('button:has-text("Start the table")');
  await page.waitForSelector('button:has-text("Record hand")');
  await shot('03-game-empty');
  await page.click('button:has-text("Record hand")');
  await page.waitForSelector('text=Who won');
  await page.click('.chip:has-text("Budi")');
  await page.click('.sec:has(.flabel:has-text("Who discarded")) .chip:has-text("Dewi")');
  await page.waitForSelector('.board');
  const tap = async (label) => page.click('.board button[aria-label="' + label + '"]');
  for (let k = 0; k < 3; k++) await tap('1 Characters');
  for (let k = 0; k < 3; k++) await tap('2 Characters');
  for (let k = 0; k < 3; k++) await tap('3 Characters');
  for (let k = 0; k < 3; k++) await tap('East');
  for (let k = 0; k < 2; k++) await tap('White dragon');
  await page.waitForSelector('.counter.ok');
  await shot('04-record-top');
  await page.locator('.sheet-body').evaluate((el) => el.scrollTo(0, 600));
  await shot('04b-record-board');
  await page.click('details.addlist summary');
  await page.click('.addbody .switch');
  await page.locator('details.addlist').scrollIntoViewIfNeeded();
  await page.locator('.sheet-body').evaluate((el) => { const d = el.querySelector('details.addlist'); el.scrollTo(0, d.offsetTop - 60); });
  await shot('05-add-pattern');
  await page.click('button:has-text("Save hand")');
  await page.waitForSelector('text=Hand saved');
  await shot('06-game-one-hand');
  await page.click('button:has-text("Keep this table")');
  await page.waitForSelector('#si-name');
  await shot('07-keep-table');
  await page.click('.seg button:has-text("Guest")');
  await shot('07b-guest');
  await page.click('.sheet-head button[aria-label="Close"]');
  await page.click('button[aria-label="Game menu"]');
  await shot('08-menu');
  await page.click('.menu button:has-text("Standings")');
  await page.waitForSelector('.srow');
  await shot('09-standings');
  await page.click('.sheet-head button[aria-label="Close"]');
  await page.click('.backbtn');
  await page.waitForSelector('.gcard');
  await shot('10-home-with-game');
  console.log('errors', errors);
  await browser.close(); server.close();
})().catch((e) => { console.error(e); process.exit(1); });
