#!/usr/bin/env python3
"""Build everything that is generated. Run from anywhere: python3 tools/build.py

  src/app.src.html + src/engine.js + src/vendor/*  ->  docs/index.html      (GitHub Pages PWA)
  tools/sw.js, tools/manifest.webmanifest           ->  docs/sw.js, docs/manifest.webmanifest
  tools/icons.py                                    ->  docs/icons/*.png     (only if missing)
  src/engine.js                                     ->  cloudflare/src/engine.js  (ESM wrapper)
  cloudflare/schema.sql                             ->  cloudflare/src/schema.js

Generated files are never edited by hand.
"""
import hashlib, os, pathlib, subprocess, sys, urllib.parse

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC, DOCS, CF, TOOLS = ROOT / 'src', ROOT / 'docs', ROOT / 'cloudflare', ROOT / 'tools'

def read(p): return p.read_text(encoding='utf-8')
def write(p, s):
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding='utf-8')
    print(f'  {p.relative_to(ROOT)}  {len(s.encode("utf-8")):,} bytes')

def main():
    api_url = read(TOOLS / 'api-url.txt').strip()
    if len(sys.argv) > 1 and sys.argv[1].startswith('http'):
        api_url = sys.argv[1]  # e.g. a local wrangler dev URL for e2e tests
    engine = read(SRC / 'engine.js')
    app = read(SRC / 'app.src.html')
    build = hashlib.sha256((engine + app + api_url).encode('utf-8')).hexdigest()[:10]

    # --- backend bundle pieces
    write(CF / 'src' / 'engine.js', '// GENERATED by tools/build.py from src/engine.js — do not edit\nconst module = { exports: {} };\n' + engine + '\nexport default module.exports;\n')
    schema = read(CF / 'schema.sql')
    write(CF / 'src' / 'schema.js', '// GENERATED by tools/build.py from cloudflare/schema.sql — do not edit\nexport const SCHEMA_SQL = ' + repr_js(schema) + ';\n')

    # --- app
    kai = '一二三四五六七八九萬東南西北中發梅蘭菊竹春夏秋冬貓鼠雞蚣莊麻雀筒索字花香港新加坡立直台灣国标自訂将將摸出銃放炮槍ツモロン点和流局起糊爆棚底'
    seen = []
    for ch in kai:
        if ch not in seen: seen.append(ch)
    vendor = '\n'.join(read(SRC / 'vendor' / f) for f in ('preact.min.umd.js', 'preact-hooks.umd.js', 'htm.umd.js'))
    out = app.replace('__KAI_TEXT__', urllib.parse.quote(''.join(seen)))
    for lite in (False, True):
        page = out
        for marker, val in (('/*__VENDOR__*/', vendor), ('/*__ENGINE__*/', engine), ('__API_URL__', api_url), ('__BUILD__', build), ('__LITE__', 'true' if lite else 'false')):
            assert marker in page, f'missing {marker} in app.src.html'
            page = page.replace(marker, val)
        d = DOCS / 'lite' if lite else DOCS
        if lite:
            page = page.replace('<title>Mahjong Scorebook</title>', '<title>Mahjong Scorebook Lite</title>').replace('href="icons/', 'href="../icons/')
        write(d / 'index.html', page)
        write(d / 'sw.js', read(TOOLS / 'sw.js').replace('__BUILD__', build + ('-lite' if lite else '')))
        man = read(TOOLS / 'manifest.webmanifest')
        if lite:
            man = man.replace('"Mahjong Scorebook"', '"Mahjong Scorebook Lite"').replace('"Scorebook"', '"Scorebook Lite"').replace('"icons/', '"../icons/').replace(' Photograph the winning hand and it reads the tiles.', '')
        write(d / 'manifest.webmanifest', man)
    write(DOCS / '.nojekyll', '')
    if not (DOCS / 'icons' / 'icon-512.png').exists():
        subprocess.check_call([sys.executable, str(TOOLS / 'icons.py')])
    print('build', build, '· API', api_url)

def repr_js(s):
    return '`' + s.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${') + '`'

if __name__ == '__main__':
    main()
